### ISSUE TITLE
MD5 used to encrypt passwords

### ISSUE THREAD

**Issue by MrSleeps** [hind-sagar-biswas/logger#1]
MD5 is really insecure and shouldn't be used for passwords..

**Comment by hind-sagar-biswas** [comment]
I apologize that I had to take this much time to notice the issue and thanks for pointing it out. 
I am currently busy, so I'll fix it by next 2 weeks.
and @MrSleeps if ya want you can also fix it and send PR

**Comment by hind-sagar-biswas** [comment]
PR to https://github.com/hind-sagar-biswas/logger/tree/1-md5-used-to-encrypt-passwords branch
